version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=libapi
      - POSTGRES_USER=libapi
      - POSTGRES_PASSWORD=libapi123
    restart: unless-stopped

  web:
    build: .
    command: /app/entrypoint-prod.sh
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - UV_SYSTEM_PYTHON=1
      - DATABASE_URL=postgresql://libapi:libapi123@db:5432/libapi
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data: