version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=libapi_dev
      - POSTGRES_USER=libapi
      - POSTGRES_PASSWORD=libapi123
    restart: unless-stopped

  web:
    build: .
    command: /app/entrypoint-dev.sh
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.venv
      - /app/.uv
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - DJANGO_DEVELOPMENT=1
      - UV_SYSTEM_PYTHON=1
      - DATABASE_URL=postgresql://libapi:libapi123@db:5432/libapi_dev
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data_dev: