version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 libAPI.wsgi:application
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - PYTHONUNBUFFERED=1
      - UV_SYSTEM_PYTHON=1
    restart: unless-stopped